In [1]:
import pandas as pd
import snscrape.modules.twitter as sntwitter

In [2]:
#trying to scrape tweets from 2022 for one user
query = 'from:unusual_whales since:2022-01-01 until:2022-12-31'
scraper = sntwitter.TwitterSearchScraper(query)

In [3]:
#create empty list to store tweets
tweets = []
#loop through tweets and append to list
for i, tweet in enumerate(scraper.get_items()):
    data = [tweet.url, tweet.date, tweet.rawContent, tweet.user.username, 
            tweet.likeCount, tweet.replyCount, tweet.retweetCount, tweet.quoteCount, 
            tweet.cashtags, tweet.hashtags, tweet.viewCount]
    tweets.append(data)

Stopping after 20 empty pages

In [4]:
#convert list to dataframe
df = pd.DataFrame(tweets, columns= ['url', 'date', 'rawContent', 'username',
                                    'likeCount', 'replyCount', 'retweetCount', 'quoteCount',
                                    'cashtags', 'hashtags', 'viewCount'])
df.head()

,url,date,rawContent,username,likeCount,replyCount,retweetCount,quoteCount,media,cashtags,hashtags,inReplyToUser,mentionedUsers,viewCount,lang,source,location
0,https://twitter.com/unusual_whales/status/1608...,2022-12-30 23:58:00+00:00,France to impose mandatory COVID tests for tra...,unusual_whales,284,36,25,4,None,None,None,None,None,114707.0,en,"<a href=""https://mobile.twitter.com"" rel=""nofo...",
1,https://twitter.com/unusual_whales/status/1608...,2022-12-30 23:17:39+00:00,SBF said: None of these are me. I'm not and c...,unusual_whales,321,63,50,13,None,None,None,https://twitter.com/unusual_whales,None,145310.0,en,"<a href=""https://mobile.twitter.com"" rel=""nofo...",
2,https://twitter.com/unusual_whales/status/1608...,2022-12-30 22:32:30+00:00,"Congratulations.\n\nIf you are reading this, y...",unusual_whales,14417,545,1287,158,None,None,None,None,None,1296489.0,en,"<a href=""https://mobile.twitter.com"" rel=""nofo...",
3,https://twitter.com/unusual_whales/status/1608...,2022-12-30 22:12:00+00:00,The Nasdaq finished in the red for a fourth st...,unusual_whales,806,54,141,16,None,None,None,None,None,162657.0,en,"<a href=""https://mobile.twitter.com"" rel=""nofo...",
4,https://twitter.com/unusual_whales/status/1608...,2022-12-30 21:54:47+00:00,"With a drop of more than 20% in 2022, the MSCI...",unusual_whales,220,9,42,2,None,None,None,https://twitter.com/unusual_whales,None,90508.0,en,"<a href=""https://mobile.twitter.com"" rel=""nofo...",

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20402 entries, 0 to 20401
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             20402 non-null  object
 1   date            20402 non-null  datetime64[ns, UTC]
 2   rawContent      20402 non-null  object
 3   username        20402 non-null  object
 4   likeCount       20402 non-null  int64
 5   replyCount      20402 non-null  int64
 6   retweetCount    20402 non-null  int64
 7   quoteCount      20402 non-null  int64
 8   media           4351 non-null   object
 9   cashtags        7961 non-null   object
 10  hashtags        161 non-null    object
 11  inReplyToUser   2095 non-null   object
 12  mentionedUsers  1049 non-null   object
 13  viewCount       975 non-null    float64
 14  lang            20402 non-null  object
 15  source          20402 non-null  object
 16  location        20402 non-null  object
dtypes: datetime64[ns, UTC](1), float64(1), int64(4), object(11)
memory usage: 2.6+ MB

In [6]:
#save to csv
data = df.to_csv('tweets.csv', index=False)