In [4]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("small_sample.csv")
df.columns

Index(['url', 'date', 'tweet', 'username', 'likeCount', 'replyCount',
       'retweetCount', 'quoteCount', 'cashtags', 'hashtags', 'stock_symbol',
       'current_value', '1min', '60min', '1day', '1week', 'positive',
       'negative', 'neutral', 'sentiment'],
      dtype='object')

In [22]:
df['prof_1min'] = np.random.uniform(-20, 20, size=len(df))
df['prof_60min'] = np.random.uniform(-20, 20, size=len(df))
df['prof_1day'] = np.random.uniform(-20, 20, size=len(df))
df['prof_1week'] = np.random.uniform(-20, 20, size=len(df))

In [23]:
df

,url,date,tweet,username,likeCount,replyCount,retweetCount,quoteCount,cashtags,hashtags,...,1day,1week,positive,negative,neutral,sentiment,prof_1min,prof_60min,prof_1day,prof_1week
0,https://twitter.com/saxena_puru/status/1567881...,2022-09-08 14:25:07+00:00,$twlo likely to generate 28-30% rev cagr over ...,saxena_puru,281,21,10,0,['TWLO'],NaN,...,NaN,NaN,0.000000,0.000000,0.993833,Neutral,-6.027593,-15.147525,-7.019371,15.468086
1,https://twitter.com/CheddarFlow/status/1574755...,2022-09-27 13:39:37+00:00,retail trader maybe this is finally the bottom...,CheddarFlow,271,10,20,7,['SPY'],NaN,...,NaN,NaN,0.000000,0.000000,0.999664,Neutral,11.605769,-17.108069,5.204940,-3.352354
2,https://twitter.com/gurgavin/status/1503422179...,2022-03-14 17:25:54+00:00,$sofi winking face with tongue,gurgavin,86,30,2,0,['SOFI'],NaN,...,NaN,NaN,0.000000,0.000000,0.999929,Neutral,15.414581,5.488015,-3.123856,-5.628670
3,https://twitter.com/CheddarFlow/status/1503385...,2022-03-14 15:02:03+00:00,$spy $189m dark pool print at 420.12,CheddarFlow,23,3,4,0,['SPY'],NaN,...,NaN,NaN,0.000000,0.000000,0.999985,Neutral,-14.010165,-14.150728,-7.869559,14.899040
4,https://twitter.com/stocktalkweekly/status/152...,2022-05-23 12:11:36+00:00,$tsla tesla will double its daily output at gi...,stocktalkweekly,94,3,5,0,['TSLA'],NaN,...,NaN,NaN,0.985855,0.000000,0.000000,Positive,-18.711088,10.112492,3.434760,4.789325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://twitter.com/alphatrends/status/1605611...,2022-12-21 17:11:07+00:00,not sure how that black anchorvwap got moved t...,alphatrends,23,3,1,0,['SPY'],NaN,...,NaN,NaN,0.000000,0.000000,0.999992,Neutral,17.082458,-13.440265,5.637464,-13.220202
996,https://twitter.com/Jake__Wujastyk/status/1496...,2022-02-23 22:47:27+00:00,$pltr pltr continues to gravitate down towards...,Jake__Wujastyk,58,7,4,0,['PLTR'],['PLTR'],...,NaN,NaN,0.000000,0.912987,0.000000,Negative,-10.621137,-8.621466,-11.563889,-1.997388
997,https://twitter.com/CheddarFlow/status/1534227...,2022-06-07 17:33:27+00:00,$aapl key channel,CheddarFlow,32,1,5,1,['AAPL'],NaN,...,NaN,NaN,0.000000,0.000000,0.999949,Neutral,8.735199,10.414869,17.484890,2.514876
998,https://twitter.com/NekozTek/status/1577701127...,2022-10-05 16:43:55+00:00,"since ethereum switched to pos algorithm, 11,5...",NekozTek,65,9,13,0,['ETH'],['Ethereum'],...,NaN,NaN,0.000000,0.000000,0.999641,Neutral,-8.622441,-8.519013,-3.216288,5.612386
999,https://twitter.com/whale_alert/status/1484654...,2022-01-21 22:31:15+00:00,"5,824,010 matic 9,934,626 usd transferred from...",whale_alert,74,9,3,0,NaN,"['MATIC', 'Binance', 'Gemini']",...,NaN,NaN,0.000000,0.000000,0.999978,Neutral,3.919188,11.479773,-17.240370,-11.823891

In [48]:
df = df.dropna(subset=['cashtags'])

In [55]:
np.unique(df["cashtags"].values)

array(["['A']", "['AAPL', 'NVDA', 'SE']", "['AAPL']", "['ADM']",
       "['AFRM']", "['AMD']", "['AMEX']", "['AMR']", "['AMZN']",
       "['APE', 'BTC']", "['APE', 'KNC', 'KAVA', 'XMR']",
       "['ARKK', 'ARKK', 'QQQ', 'QQQ', 'SMH', 'SPY', 'ARKK']", "['ARKK']",
       "['BABA']", "['BLK']", "['BLXM']", "['BTC', 'ETH']", "['BTC']",
       "['BTU']", "['CAT']", "['CCL']", "['CELH']", "['CENX']",
       "['CHPT']", "['CLF']", "['CLX']", "['CMCSA']", "['COMPQ', 'ARKK']",
       "['CRWD', 'S']", "['CSCO', 'SYY']", "['CSCO']", "['CYBR']",
       "['DDOG']", "['DIS']", "['DOW']", "['ET', 'TSLA', 'NVDA', 'QQQ']",
       "['ETH', 'BTC']", "['ETH', 'FB']", "['ETH']", "['ETHBTC']",
       "['F']", "['FB', 'AAPL', 'AMZN', 'DIS']", "['FB']", "['GETY']",
       "['GOLD']", "['GOOGL']", "['GPS']", "['GRPN']",
       "['INTC', 'TSEM', 'TSEM', 'TSEM']", "['ISEE']", "['ISRG']",
       "['IWM']", "['JPM']", "['KHC']", "['KNC']", "['KRNT']", "['LAC']",
       "['LCID']", "['LINK', 'DOGE']", "['LIT']", "['LMT']", "['LOOKS']",
       "['LPI']", "['LTHM']", "['LUNA', 'UST', 'LUNA']", "['LUNA']",
       "['MARA', 'RIOT']", "['META']", "['METIS']",
       "['MGNI', 'USER', 'TGTX', 'GLYC', 'GRWG', 'APPS', 'BAND', 'VAPO', 'UFAB', 'CLVS', 'RPAY', 'EVER', 'RDFN', 'TLS', 'OPRT', 'RYAM', 'NEO', 'APYX', 'TSP']",
       "['MRVL']", "['MSFT']", "['MTDR']", "['MTRG']",
       "['MU', 'AMD', 'NVDA']", "['MU']", "['NDX', 'SPX']", "['NEAR']",
       "['NFLX']", "['NKE']", "['NQ', 'ES']", "['NVAX']", "['NVDA']",
       "['NWC', 'XHV', 'ALGO', 'SOL', 'VET', 'OM']", "['PARA']",
       "['PCRFY', 'TSLA']",
       "['PG', 'MSFT', 'UNH', 'CRM', 'JNJ', 'WMT', 'MMM', 'CAT', 'BA', 'AXP', 'CSCO', 'INTC', 'JPM', 'DIS']",
       "['PL']", "['PLTR']",
       "['PTON', 'ASAN', 'LU', 'DOCS', 'ACH', 'SQM', 'TOST', 'ZEN', 'DIDI', 'NU', 'HUBS', 'AA']",
       "['PTON']", "['PYPL']", "['QQQ', 'IWM']", "['QQQ']", "['ROKU']",
       "['SARK']", "['SBUX']", "['SCCO']", "['SKLZ']", "['SLB']",
       "['SNAP', 'BILL', 'U', 'AMZN', 'CHWY', 'APP', 'PINS', 'TTD', 'PCTY', 'ROKU', 'SPOT', 'AFRM']",
       "['SNAP']", "['SNX']", "['SOFI']",
       "['SOL', 'DOT', 'AVAX', 'LUNA']", "['SOL']", "['SPX', 'DXY']",
       "['SPX']", "['SPY', 'DJI']", "['SPY']", "['SQ']", "['SQQQ']",
       "['TDOC']", "['TECK']", "['TSLA']", "['TSM']", "['TWTR']", "['U']",
       "['UBER']", "['ULCC']", "['UNH']", "['UPS']", "['UPST']",
       "['UST', 'UST', 'LUNA', 'LUNA', 'UST']", "['UST']", "['VIDT']",
       "['VIEW']", "['VIX']", "['VRA']", "['WMT']", "['XBI']", "['XRP']",
       "['YUM']"], dtype=object)

In [60]:
import re
def clean_cashtgs(st):
    letters = re.findall('[A-Za-z]+', st)
    return ' '.join(letters)

In [61]:
clean_cashtgs("['MGNI', 'USER', 'TGTX', 'GLYC', 'GRWG', 'APPS', 'BAND', 'VAPO', 'UFAB', 'CLVS', 'RPAY', 'EVER', 'RDFN', 'TLS', 'OPRT', 'RYAM', 'NEO', 'APYX', 'TSP']")

'MGNI USER TGTX GLYC GRWG APPS BAND VAPO UFAB CLVS RPAY EVER RDFN TLS OPRT RYAM NEO APYX TSP'

In [64]:
df["cashtags"] = df["cashtags"].apply(clean_cashtgs)

/tmp/ipykernel_5933/4203094212.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["cashtags"] = df["cashtags"].apply(clean_cashtgs)

In [76]:
df[df["cashtags"] == "MSFT"]

,url,date,tweet,username,likeCount,replyCount,retweetCount,quoteCount,cashtags,hashtags,...,1day,1week,positive,negative,neutral,sentiment,prof_1min,prof_60min,prof_1day,prof_1week
82,https://twitter.com/TommyThornton/status/15850...,2022-10-25 22:20:01+00:00,it’s happening. $msft guidance is weaker than ...,TommyThornton,183,18,32,6,MSFT,NaN,...,NaN,NaN,0.000000,1.0,0.0,Negative,8.163401,5.028809,11.967486,11.472319
837,https://twitter.com/StockMKTNewz/status/158494...,2022-10-25 16:21:13+00:00,microsoft $msft reports earnings today after t...,StockMKTNewz,51,0,4,3,MSFT,NaN,...,NaN,NaN,0.994921,0.0,0.0,Positive,-5.246748,-14.135719,9.486120,-11.268656

In [67]:
df.to_csv('smaple_with_random profits.csv')