In [130]:
import pandas as pd
import re
from sklearn.preprocessing import MinMaxScaler

In [89]:
    df = pd.read_csv("actionable_data.csv")

In [90]:
df.columns

Index(['Unnamed: 0', 'url', 'date', 'tweet', 'username', 'likeCount',
       'replyCount', 'retweetCount', 'quoteCount', 'cashtags', 'hashtags',
       'stock_symbol', 'current_value', '1min', '60min', '1day', '1week',
       'positive', 'negative', 'neutral', 'sentiment'],
      dtype='object')

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16496 entries, 0 to 16495
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     16496 non-null  int64
 1   url            16496 non-null  object
 2   date           16496 non-null  object
 3   tweet          16496 non-null  object
 4   username       16496 non-null  object
 5   likeCount      16496 non-null  int64
 6   replyCount     16496 non-null  int64
 7   retweetCount   16496 non-null  int64
 8   quoteCount     16496 non-null  int64
 9   cashtags       13876 non-null  object
 10  hashtags       3900 non-null   object
 11  stock_symbol   0 non-null      float64
 12  current_value  0 non-null      float64
 13  1min           0 non-null      float64
 14  60min          0 non-null      float64
 15  1day           0 non-null      float64
 16  1week          0 non-null      float64
 17  positive       16496 non-null  float64
 18  negative       16496 non-null  float64
 19  neutral        16496 non-null  float64
 20  sentiment      16496 non-null  object
dtypes: float64(9), int64(5), object(7)
memory usage: 2.6+ MB

In [92]:
def clean_cashtags(st):
    letters = re.findall('[A-Za-z]+', st)
    return ' '.join(letters)

In [93]:
df = df.dropna(subset=["cashtags"])

In [94]:
df["cashtags"] = df["cashtags"].apply(clean_cashtags)

In [104]:
def del_timestamp(st):
    return st.replace("+00:00", "")

In [105]:
df["date"] = df["date"].apply(del_timestamp)

In [110]:
df["date"] = pd.to_datetime(df['date'])

In [113]:
df.index = df.pop('date')

KeyError: 'date'

In [116]:
df[df["cashtags"] == "MSFT"]

,Unnamed: 0,url,tweet,username,likeCount,replyCount,retweetCount,quoteCount,cashtags,hashtags,stock_symbol,current_value,1min,60min,1day,1week,positive,negative,neutral,sentiment
date,,,,,,,,,,,,,,,,,,,,
2022-01-04 19:17:57,74,https://twitter.com/johnscharts/status/1478445...,$msft breaching 2050 ma,johnscharts,14,2,1,0,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.713463,0.0,Negative
2022-01-11 16:16:38,236,https://twitter.com/johnscharts/status/1480936...,"$msft call flow 312.5315. 100 ma in path, so r...",johnscharts,3,0,0,0,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.701916,0.000000,0.0,Positive
2022-01-12 01:05:30,262,https://twitter.com/Jake__Wujastyk/status/1481...,$msft mfst another top watch into tomorrow.,Jake__Wujastyk,383,14,35,3,MSFT,['MFST'],NaN,NaN,NaN,NaN,NaN,NaN,0.949306,0.000000,0.0,Positive
2022-01-19 15:01:38,429,https://twitter.com/johnscharts/status/1483816...,$msft up 44%. np,johnscharts,5,1,0,0,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999985,0.000000,0.0,Positive
2022-01-31 15:09:34,732,https://twitter.com/johnscharts/status/1488167...,$msft updat from watchlist. feb 4 310 up 26%,johnscharts,5,0,0,1,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999813,0.000000,0.0,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-25 22:20:01,15192,https://twitter.com/TommyThornton/status/15850...,it’s happening. $msft guidance is weaker than ...,TommyThornton,183,18,32,6,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.0,Negative
2022-10-26 13:33:18,15212,https://twitter.com/gurgavin/status/1585263300...,microsoft sinks in biggest intraday drop since...,gurgavin,153,3,11,3,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.538974,0.0,Negative
2022-11-14 16:00:36,15789,https://twitter.com/StockMKTNewz/status/159218...,microsoft unveils software to ease supply-chai...,StockMKTNewz,50,5,4,3,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.999600,0.0,Negative
2022-12-14 13:01:56,16244,https://twitter.com/StockMKTNewz/status/160301...,microsoft $msft in pact w viasat to quickly sc...,StockMKTNewz,34,2,4,1,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.993852,0.000000,0.0,Positive
2022-12-27 19:30:15,16439,https://twitter.com/StockMKTNewz/status/160782...,microsoft $msft has announced it’s making exce...,StockMKTNewz,90,4,4,4,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.978783,0.000000,0.0,Positive

In [120]:
df_stocks = pd.read_csv("AAPL.csv")
df_stocks.columns

Index(['time', 'open', 'high', 'low', 'close', 'volume', 'symbol'], dtype='object')

In [124]:
df_stocks = df_stocks[['time', 'close']]
df_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235156 entries, 0 to 235155
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   time    235156 non-null  object
 1   close   235156 non-null  float64
dtypes: float64(1), object(1)
memory usage: 3.6+ MB

In [127]:
df_stocks["time"] = pd.to_datetime(df_stocks["time"])

In [128]:
df_stocks.index = df_stocks.pop("time")

In [129]:
df_stocks

                          close
time
2021-12-13 04:01:00  178.860090
2021-12-13 04:02:00  179.197188
2021-12-13 04:03:00  179.365737
2021-12-13 04:04:00  179.385566
2021-12-13 04:05:00  179.256676
...                         ...
2023-02-03 19:55:00  154.095401
2023-02-03 19:56:00  154.105286
2023-02-03 19:57:00  154.095301
2023-02-03 19:59:00  154.115270
2023-02-03 20:00:00  154.155210

[235156 rows x 1 columns]

In [132]:
scaller = MinMaxScaler()

df_stocks["close_scalled"] = scaller.fit_transform(df_stocks[["close"]])

In [133]:
df_stocks

                          close  close_scalled
time
2021-12-13 04:01:00  178.860090       0.949212
2021-12-13 04:02:00  179.197188       0.955046
2021-12-13 04:03:00  179.365737       0.957962
2021-12-13 04:04:00  179.385566       0.958306
2021-12-13 04:05:00  179.256676       0.956075
...                         ...            ...
2023-02-03 19:55:00  154.095401       0.520636
2023-02-03 19:56:00  154.105286       0.520807
2023-02-03 19:57:00  154.095301       0.520634
2023-02-03 19:59:00  154.115270       0.520980
2023-02-03 20:00:00  154.155210       0.521671

[235156 rows x 2 columns]

In [134]:
df

,Unnamed: 0,url,tweet,username,likeCount,replyCount,retweetCount,quoteCount,cashtags,hashtags,stock_symbol,current_value,1min,60min,1day,1week,positive,negative,neutral,sentiment
date,,,,,,,,,,,,,,,,,,,,
2022-01-01 04:22:22,1,https://twitter.com/LilMoonLambo/status/147713...,$eth bears died a painful death this yearlet’s...,LilMoonLambo,33,5,4,0,ETH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.997282,0.0,Negative
2022-01-01 10:28:50,2,https://twitter.com/cryptomanran/status/147722...,"$ftm just hit 1,5m addresses. more interesting...",cryptomanran,1601,132,237,16,FTM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.886819,0.000000,0.0,Positive
2022-01-01 14:00:02,3,https://twitter.com/johnscharts/status/1477278...,$pfe earningssales acceleration,johnscharts,9,0,0,0,PFE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.0,Positive
2022-01-01 17:30:35,4,https://twitter.com/CryptoGodJohn/status/14773...,2022 will be the year of $htrall kings with be...,CryptoGodJohn,656,46,85,14,HTR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.996068,0.000000,0.0,Positive
2022-01-01 17:36:38,5,https://twitter.com/CryptoGodJohn/status/14773...,$avax looks ready to rip,CryptoGodJohn,255,18,10,2,AVAX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.993931,0.000000,0.0,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-30 19:11:04,16491,https://twitter.com/mikealfred/status/16089035...,author i trimmed pepsi at $185. no longer lov...,mikealfred,1,2,0,0,PEP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.970429,0.000000,0.0,Positive
2022-12-30 20:49:37,16492,https://twitter.com/StockMKTNewz/status/160892...,nlrb claims tesla $tsla illegally told staff t...,StockMKTNewz,39,7,4,0,TSLA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.508475,0.0,Negative
2022-12-30 21:03:42,16493,https://twitter.com/StockMKTNewz/status/160893...,the sampp 500 $spy and nasdaq 100 $qqq both cl...,StockMKTNewz,97,5,25,1,SPY QQQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.999628,0.0,Negative
2022-12-30 21:04:59,16494,https://twitter.com/StockMKTNewz/status/160893...,the sampp 500 $spy saw its market cap drop by ...,StockMKTNewz,60,6,12,0,SPY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.891084,0.0,Negative
2022-12-30 21:17:25,16495,https://twitter.com/StockMKTNewz/status/160893...,the nasdaq 100 closed the year down more than ...,StockMKTNewz,83,8,32,2,DIA SPY QQQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.999996,0.0,Negative

In [135]:
merged_df = pd.merge(df, df_stocks, left_index=True, right_index=True)

In [145]:
merged_df

,Unnamed: 0,url,tweet,username,likeCount,replyCount,retweetCount,quoteCount,cashtags,hashtags,...,1min,60min,1day,1week,positive,negative,neutral,sentiment,close,close_scalled
2022-01-04 12:23:00,58,https://twitter.com/Jake__Wujastyk/status/1478...,$fslr fslr nice upgrade this morning.,Jake__Wujastyk,49,6,0,0,FSLR,['FSLR'],...,NaN,NaN,NaN,NaN,0.999999,0.000000,0.0,Positive,178.810517,0.948354
2022-01-04 18:05:00,8159,https://twitter.com/mikealfred/status/14784272...,absolute bloodbath at ark today. every stock i...,mikealfred,8,4,0,0,COIN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.999245,0.0,Negative,177.987602,0.934113
2022-01-06 15:16:00,129,https://twitter.com/johnscharts/status/1479109...,$coin from chat 225 puts up 27%,johnscharts,1,0,1,0,COIN,NaN,...,NaN,NaN,NaN,NaN,0.851857,0.000000,0.0,Positive,171.323378,0.818782
2022-01-07 16:51:00,8266,https://twitter.com/stocktalkweekly/status/147...,$hlgn now down nearly -60% since shortputs wer...,stocktalkweekly,14,0,0,0,HLGN,NaN,...,NaN,NaN,NaN,NaN,0.990228,0.000000,0.0,Positive,170.462391,0.803882
2022-01-11 16:40:00,238,https://twitter.com/Jake__Wujastyk/status/1480...,$roku roku beautiful setup for a strong move i...,Jake__Wujastyk,56,5,2,0,ROKU,['ROKU'],...,NaN,NaN,NaN,NaN,1.000000,0.000000,0.0,Positive,173.605331,0.858273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-15 16:40:00,7862,https://twitter.com/CheddarFlow/status/1603429...,mike wilson $ms “people assume earnings are go...,CheddarFlow,53,2,10,5,MS,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.997285,0.0,Negative,135.950803,0.206627
2022-12-16 14:57:00,7875,https://twitter.com/johnscharts/status/1603766...,$meta flow noted in morning chat dec 16 122 mo...,johnscharts,2,0,0,0,META,NaN,...,NaN,NaN,NaN,NaN,0.814894,0.000000,0.0,Positive,133.821741,0.169782
2022-12-22 15:46:00,16385,https://twitter.com/CryptoKaleo/status/1605952...,$tsla decline beginning to accelerate,CryptoKaleo,58,9,3,1,TSLA,NaN,...,NaN,NaN,NaN,NaN,0.920784,0.000000,0.0,Positive,131.094349,0.122582
2022-12-22 19:30:00,16391,https://twitter.com/CryptoKaleo/status/1606009...,"bitcoin $btcfirst and foremost, i believe the ...",CryptoKaleo,127,19,5,1,BTC,['Bitcoin'],...,NaN,NaN,NaN,NaN,0.628704,0.000000,0.0,Positive,131.233959,0.124998
2022-12-28 14:09:00,8049,https://twitter.com/Jake__Wujastyk/status/1608...,anyone else remember that elon has been eccent...,Jake__Wujastyk,310,52,19,5,TSLA,['Tesla'],...,NaN,NaN,NaN,NaN,0.000000,0.999941,0.0,Negative,126.806863,0.048383

In [141]:
merged_short = merged_df[['tweet', 'username', 'likeCount', 'replyCount',
       'retweetCount', 'sentiment', 'close']]

In [143]:
merged_short

,tweet,username,likeCount,replyCount,retweetCount,sentiment,close
2022-01-04 12:23:00,$fslr fslr nice upgrade this morning.,Jake__Wujastyk,49,6,0,Positive,178.810517
2022-01-04 18:05:00,absolute bloodbath at ark today. every stock i...,mikealfred,8,4,0,Negative,177.987602
2022-01-06 15:16:00,$coin from chat 225 puts up 27%,johnscharts,1,0,1,Positive,171.323378
2022-01-07 16:51:00,$hlgn now down nearly -60% since shortputs wer...,stocktalkweekly,14,0,0,Positive,170.462391
2022-01-11 16:40:00,$roku roku beautiful setup for a strong move i...,Jake__Wujastyk,56,5,2,Positive,173.605331
...,...,...,...,...,...,...,...
2022-12-15 16:40:00,mike wilson $ms “people assume earnings are go...,CheddarFlow,53,2,10,Negative,135.950803
2022-12-16 14:57:00,$meta flow noted in morning chat dec 16 122 mo...,johnscharts,2,0,0,Positive,133.821741
2022-12-22 15:46:00,$tsla decline beginning to accelerate,CryptoKaleo,58,9,3,Positive,131.094349
2022-12-22 19:30:00,"bitcoin $btcfirst and foremost, i believe the ...",CryptoKaleo,127,19,5,Positive,131.233959
2022-12-28 14:09:00,anyone else remember that elon has been eccent...,Jake__Wujastyk,310,52,19,Negative,126.806863

In [144]:
df_stocks

                          close  close_scalled
time
2021-12-13 04:01:00  178.860090       0.949212
2021-12-13 04:02:00  179.197188       0.955046
2021-12-13 04:03:00  179.365737       0.957962
2021-12-13 04:04:00  179.385566       0.958306
2021-12-13 04:05:00  179.256676       0.956075
...                         ...            ...
2023-02-03 19:55:00  154.095401       0.520636
2023-02-03 19:56:00  154.105286       0.520807
2023-02-03 19:57:00  154.095301       0.520634
2023-02-03 19:59:00  154.115270       0.520980
2023-02-03 20:00:00  154.155210       0.521671

[235156 rows x 2 columns]